-- Active: 1747592286665@@127.0.0.1@3306
CREATE TABLE "FERRAMENTAS" (
    "ID_FERRAMENTA" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "NOME" VARCHAR(255) NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "DT_CADASTRO" TIMESTAMP DEFAULT (DATETIME('now', '-3 hours')) NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL, -- Usuário que cadastrou a ferramenta
    "FERRAMENTA_DISPONIVEL" INT DEFAULT 1 NOT NULL, -- Ferramenta disponível para empréstimo no presente momento
    "FOTO" TEXT DEFAULT NULL -- URL da foto da ferramenta
);
