-- Active: 1747592286665@@127.0.0.1@3306
CREATE TABLE "REGISTROS" (
    "ID_REGISTRO" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_FERRAMENTA" integer NOT NULL UNIQUE,
    "DT_EMPRESTIMO_PREVISTA" TIMESTAMP,
    "DT_DEVOLUCAO_PREVISTA" TIMESTAMP,
    "DT_RETIRADA" TIMESTAMP DEFAULT NULL,
    "DT_RETORNO" TIMESTAMP DEFAULT NULL,
    "FERRAMENTA_DISPONIVEL" INT DEFAULT 1 NOT NULL,
);