-- Active: 1747592286665@@127.0.0.1@3306
CREATE TABLE "REGISTROS" (
    "ID_REGISTRO" INTEGER PRIMARY KEY AUTOINCREMENT,
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_FERRAMENTA" integer NOT NULL UNIQUE,
    "DT_EMPRESTIMO" TIMESTAMP,
    "DT_DEVOLUCAO" TIMESTAMP,
    "AUTORIZADO" INT DEFAULT 0 NOT NULL,
    "FINALIZADO" INT DEFAULT 0 NOT NULL,
);