-- Active: 1747592286665@@127.0.0.1@3306
CREATE TABLE "FERRAMENTAS" (
    "ID_USUARIO" INTEGER NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL UNIQUE,
    "ID_FERRAMENTA" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "NOME" VARCHAR(255) NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "DT_CADASTRO" TIMESTAMP DEFAULT current_timestamp,
);
